version: '3.7'
services:
  api:
    build: ./api
    ports:
        - 5000:80
  webapp:
    image: dan0n/flask-alpine:python3.6
    build: ./webapp
    ports:
      - 80:80
    depends_on: 
      - mqtt 
  mqtt:
    image: toke/mosquitto
    ports:
      - 9001:1883