version: '3.7'
services:
  mqttbroker:
    image: toke/mosquitto
    expose:
      - 9001
  webapp:
    build: ./webapp
    ports:
      - 80:80
    environment:
      - PG_PASSWORD=student_password
      - PG_USER=student_user
      - PG_DATABASE=labo
      - PG_PORT=5432
      - PG_HOST=postgres
    depends_on:
      - postgres
  postgres:
    image: 'postgres:12.1-alpine'
    environment:
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_USER=student_user
      - POSTGRES_DB=labo
  fastapi:
    build: ./fastapi
    ports:
      - 5000:80
    environment:
      - PG_PASSWORD=student_password
      - PG_USER=student_user
      - PG_DATABASE=labo
      - PG_PORT=5432
      - PG_HOST=postgres
    depends_on:
      - postgres