version: '3.6'
services:
  api:
    build: ./api
    ports:
        - 5000:80
    restart: always
    volumes:
      - ./api/app/data:/project-api
  webapp:
    image: dan0n/flask-alpine:python3.6
    build: ./webapp
    ports:
      - 80:80
    restart: always
    